# Default initial positions for jaka_s12's ros2_control fake system

initial_positions:
  joint_1: 0.0
  joint_2: 2.513
  joint_3: -2.471
  joint_4: -0.541
  joint_5: -1.5708
  joint_6: 0.7854
  joint_7: 0.00